### ISSUE TITLE
endpoint is not thread safe

### ISSUE THREAD

**Issue by feexon** [ericminio/yose-java#3]
excuse me.
Hi :smiley: ,I'm a young **China** man who send an email to your gmail.I found a minor mistakes in Endpoint,it's not thread safe!is this a problem?I don't known if that can help get you?

**Comment by ericminio** [comment]
It's not a problem for me in the context of Yose the game

**Comment by feexon** [comment]
thanks,your answer make me think TDD rule again -- write code only make the test pass.
